# Linear algebra for data science practical Exercises

## chapter *2*:

In [8]:
import numpy as np
import numpy.linalg as la

- vector arithmetic

Exercise 2-1.
The online code repository is “missing” code to create Figure 2-2. (It’s not really
missing—I moved it into the solution to this exercise.) So, your goal here is to write
your own code to produce Figure 2-2.

In [2]:
v = np.array([1,2])
m = np.array([4,-6])
mvplus = v + m
mvmins = m - v
print("v + m =", mvplus)
print("m - v =" , mvmins)


v + m = [ 5 -4]
m - v = [ 3 -8]


- vector norm

Exercise 2-2.
Write an algorithm that computes the norm of a vector by translating Equation
2-7 into code. Confirm, using random vectors with different dimensionalities and
orientations, that you get the same result as np.linalg.norm(). This exercise is
designed to give you more experience with indexing NumPy arrays and translating
formulas into code; in practice, it’s often easier to use np.linalg.norm().

In [3]:
#v = sqrt for sigma of  v_i^2
#np.sqrt..np.sum..v**2
def normofvect(v):
    return np.sqrt(np.sum(v**2))
#we create the vector called w
w = np.array([0,0,1])
#recall the fuctaion
print("the norm of w is",normofvect(w))

the norm of w is 1.0


- vector normalization

Exercise 2-3.
Create a Python function that will take a vector as input and output a unit vector in
the same direction. What happens when you input the zeros vecto

In [4]:
#normalized vector = v / norm of v
#to get norm v = sqrt for (a^2 + b^2 + c^2)
def noromect(v):
    mv = np.linalg.norm(v)
    return v / mv
#np.sqrt(np.sum(v**2))

w = np.array([0,2,4], dtype=float)
print("the normalized vector of w is:\n",noromect(w))

the normalized vector of w is:
 [0.         0.4472136  0.89442719]


- create any-norm vector

Exercise 2-4.
You know how to create unit vectors; what if you want to create a vector of any
arbitrary magnitude? Write a Python function that will take a vector and a desired
magnitude as inputs and will return a vector in the same direction but with a
magnitude corresponding to the second input.

In [5]:
def createnoramvect(v,mg):
    mu = np.linalg.norm(v)
    return mg * v/mu

w = np.array([1,8,3])
result = createnoramvect(w,4)
print(result)

[0.46499055 3.71992444 1.39497166]


- transpose operation

Exercise 2-5.
Write a for loop to transpose a row vector into a column vector without using a
built-in function or method such as np.transpose() or v.T. This exercise will help
you create and index orientation-endowed vectors

In [6]:
v = np.array([[1,2,3]])

vt = np.zeros((3,1))

for i in range(v.shape[1]):
    vt[i,0] = v[0,i]

print(v)
print()
print(vt)

[[1 2 3]]

[[1.]
 [2.]
 [3.]]


- dot product and vector norm 

Exercise 2-6 Here is an interesting fact: you can compute the squared norm of a vector as the dot
product of that vector with itself. Look back to Equation 2-8 to convince yourself of
this equivalence. Then confirm it using Python.

In [7]:
c = np.random.randn(5)
sqrnrm = np.dot(c,c)
sqrnrm

9.53780907378502

- dot product commutivity

Exercise 2-7 Write code to demonstrate that the dot product is commutative. Commutative means
that a × b = b × a, which, for the vector dot product, means that a
T
b = b
T
a. After
demonstrating this in code, use equation Equation 2-9 to understand why the dot
product is commutative.

In [8]:
n = 2
a = np.random.randn(n,1)
b = np.random.randn(n,1)

atb = a.T @ b
bta = a @ b.T
atb - bta

array([[0.17500313, 0.21858737],
       [0.07498515, 0.1480196 ]])

- orthogonal projection

Exercise 2-8 Write code to produce Figure 2-6. (Note that your solution doesn’t need to look
exactly like the figure, as long as the key elements are present.)

In [9]:
m1 = np.array([1,2])
m2 = np.array([0.5,5])

beat = np.dot(m1.T, m2) / np.dot(m2.T,m2)

project_m1m2 = beat * m2

w = m1 - project_m1m2
print(f"Dot product (w . m2): {np.dot(w, m2)}")
# 3.3306690738754696e-16 = 0

Dot product (w . m2): -3.3306690738754696e-16


- vector decomposition

Exercise 2-9.
Implement orthogonal vector decomposition. Start with two random-number vectors
t and r, and reproduce Figure 2-8 (note that your plot will look somewhat different
due to random numbers). Next, confirm that the two components sum to tand that
t ⊥ r and t ∥ r are orthogonal.

In [22]:
t = np.random.randn(2)
r = np.random.randn(2)

para_t = r * (np.dot(r,t) / np.dot(r,r))
perp_t = t - para_t

print(t)
print(r)
print(para_t)
print(perp_t)

print(np.dot(para_t,perp_t)) 
#1.1102230246251565e-16 = 0


[-1.19218614 -0.21623464]
[1.67602505 0.54213605]
[-1.14258235 -0.36958581]
[-0.04960379  0.15335117]
-2.983724378680108e-16


- debugging decompositions

Exercise 2-10.
An important skill in coding is finding bugs. Let’s say there is a bug in your code
such that the denominator in the projection scalar of Equation 2-13 is tT
t instead of
rT
r (an easy mistake to make, speaking from personal experience while writing this
chapter!). Implement this bug to check whether it really deviates from the accurate
code. What can you do to check whether the result is correct or incorrect? (In coding,
confirming code with known results is called sanity-checking.)

$$\beta = \frac{t \cdot r}{r \cdot r} = \frac{t^T r}{\|r\|^2}$$

$$t_{\parallel r} = \beta \times r$$$$t_{\perp r} = t - t_{\parallel r}$$

In [34]:
t = np.random.randn(2)
r = np.random.randn(2)

# حساب المعامل (Scalar)
beta = (np.dot(t,r) / np.dot(r,r))

# المكون الموازي (Parallel Component)
para_t = beta * r

# المكون العمودي (Perpendicular Component)
perp_t = t - para_t


is_orthogonal = np.isclose(np.dot(para_t, perp_t), 0, atol=1e-15)
print(int(is_orthogonal))
print(f"Is it truly orthogonal? {is_orthogonal}")

1
Is it truly orthogonal? True


## chapter *3*

- inear weighted combination 

Exercise 3-1.
Rewrite the code for linear weighted combination, but put the scalars in a list and the
vectors as elements in a list (thus, you will have two lists, one of scalars and one of
NumPy arrays). Then use a for loop to implement the linear weighted combination
operation. Initialize the output vector using np.zeros(). Confirm that you get the
same result as in the previous code.

$$Result = (w_1 \times v_1) + (w_2 \times v_2) + (w_3 \times v_3)$$

In [8]:
l1 = 3
l2 = -2
l3 = 1
v1 = np.array([1,2,3])
v2 = np.array([3,-2,0])
v3 = np.array([6,7,-5])

scaler = [l1,l2,l3]
vector = [v1,v2,v3]

lincom = np.zeros(len(v1))

for s,v in zip(scaler,vector):
    lincom += s*v
    
print("the inear weighted combination:", lincom)

the inear weighted combination: [ 3. 17.  4.]


- expanding linear combinations 

Exercise 3-2.
Although the method of looping through lists in the previous exercise is not as
efficient as matrix-vector multiplication, it is more scalable than without a for loop.
You can explore this by adding additional scalars and vectors as elements in the lists.
What happens if the new added vector is in ℝ
4 instead of ℝ 3? And what happens if you have more scalars than vectors?

In [16]:
l1 = 3
l2 = -2
l3 = 1
v1 = np.array([1,2,3])
v2 = np.array([3,-2,0])
v3 = np.array([6,7,-5])
v4 = np.array([-3,-2,1])

scaler = [l1,l2,l3]
vector = [v1,v2,v3]

lincom = np.zeros(len(v1))

for i in range(len(scaler)):
    lincom += scaler[i] * vector[i]
    
print("the inear weighted combination:", lincom)

the inear weighted combination: [ 3. 17.  4.]


- visualizing subspaces

Exercise 3-3.
In this exercise, you will draw random points in subspaces. This will help reinforce
the idea that subspaces comprise any linear weighted combination of the spanning
vectors. Define a vector set containing one vector [1, 3]. Then create 100 numbers
drawn randomly from a uniform distribution between −4 and +4. Those are your
random scalars. Multiply the random scalars by the basis vector to create 100 random
points in the subspace. Plot those points.
Next, repeat the procedure but using two vectors in ℝ
3
: [3, 5, 1] and [0, 2, 2]. Note
that you need 100 × 2 random scalars for 100 points and two vectors. The resulting
random dots will be on a plane. Figure 3-7 shows what the results will look like (it’s
not clear from the figure that the points lie on a plane, but you’ll see this when you
drag the plot around on your screen).
I recommend using the plotly library to draw the dots, so you can click-drag the 3D
axis around. Here’s a hint for getting it to work:
import plotly.graph_objects as go
fig = go.Figure( data=[go.Scatter3d(
 x=points[:,0], y=points[:,1], z=points[:,2],
 mode='markers' )])
fig.show()
Finally, repeat the ℝ
3
 case but setting the second vector to be 1/2 times the first.


In [26]:
a = np.array([1,2])

limit = [-4,4]

scaler = np.random.uniform(low=limit[0],high=limit[1],size=100)

# visualizing  code

array([-0.82764844,  3.29672621, -0.69434053,  1.47592344,  3.39394968,
        0.88758824, -3.61528383,  1.84608375,  3.4887391 , -1.15905631,
       -0.59989489,  3.32690958,  3.98152166,  1.39018798,  3.47758422,
        3.0764459 , -2.68396647,  3.05031323, -1.97731652,  1.68556432,
        0.15933792,  0.41063732, -2.43477345,  1.76780568,  2.20710771,
       -3.64657465,  2.40716858,  0.29422061, -1.5471534 ,  3.98533803,
        2.39370626,  2.64824898, -2.08144043, -3.95103664, -2.56957336,
        0.40466723, -0.25278581,  2.57954055, -1.01235271,  1.15940051,
       -1.88116259,  1.84964704, -0.50150388,  0.18431861,  3.3133196 ,
        1.92528376, -3.66351738, -0.30491335, -2.34454715,  2.25146842,
       -3.83362009, -3.97444226, -1.48879928, -3.35094693, -0.05043739,
        0.13591012,  2.7750285 ,  2.99244513,  1.46105596,  2.47201034,
       -3.10362832,  1.41742291,  1.41451427,  0.65978029, -0.11634406,
        3.25515075, -2.25043864, -3.3788693 , -1.18550756, -3.46

# chapter 9

- properties of square Q

Exercise 9-1 A square Q has the following equalities: 
Q.TQ = Q.QT= Q‐1.Q = Q.Q‐1 = I 
Demonstrate this in code by computing Qfrom a random-numbers matrix, then compute QT and Q−1. Then show that all four expressions produce the identity matrix.

In [34]:
A = np.random.randn(3,3)

Q, R = la.qr(A)

print("Orthogonal Matrix Q:\n", Q)
print("\nUpper Triangular Matrix R:\n", R)

Qt = Q.T
Qi = la.inv(Q)

#Qt * Q
op1 = np.round(Qt @ Q,8)
# Q*Qt
op2 = np.round(Q @ Qt,8)
# Q-1*Q
op3 = np.round(Qi@ Q,8)
# Q*Q-1
op4 = np.round(Q @ Qi,8)

if np.allclose(op1, op2) and np.allclose(op1, op3):
    print("TRUE")
else:
    print("FALSE")
    
op1

Orthogonal Matrix Q:
 [[-0.47676756 -0.38397827 -0.79072965]
 [ 0.79781918 -0.5666575  -0.20587332]
 [-0.36902201 -0.72901301  0.57650914]]

Upper Triangular Matrix R:
 [[ 1.52625591 -0.73677489  0.10357751]
 [ 0.          0.62026115  0.26914268]
 [ 0.          0.          0.77647152]]
TRUE


array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [-0., -0.,  1.]])